#!/usr/bin/env bash
# Читает carusel-memory/*.env.local → YAML для gcloud run deploy --env-vars-file

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MEMORY="$ROOT/carusel-memory"

read_env() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%#*}"
    line="$(echo "$line" | xargs)"
    [[ -z "$line" || "$line" != *"="* ]] && continue
    local key="${line%%=*}"
    local val="${line#*=}"
    val="${val%\"}"; val="${val#\"}"
    val="${val%\'}"; val="${val#\'}"
    printf '%s: "%s"\n' "$key" "$val"
  done < "$file"
}

{
  echo "KARUSELKA_RUNTIME: cloud"
  echo "WORKER_STATE_BACKEND: dropbox"
  echo "ACCOUNTS_PAIRS_PATH: /app/config/accounts-pairs.json"
  echo "WORKER_STATE_DROPBOX_PATH: /Content_Plan/.karuselka/worker-state.json"
  echo "CLOUD_RUN_RENDER_URL: https://ai-carousel-renderer-861393245289.europe-west1.run.app/generate-carousel"
  echo "RENDER_TIMEOUT_SEC: \"1200\""
  read_env "$MEMORY/airtable.env.local"
  read_env "$MEMORY/dropbox.env.local"
  read_env "$MEMORY/zernio.env.local"
  read_env "$MEMORY/telegram.env.local"
  read_env "$MEMORY/cloud-worker.env.local"
  if [[ -f "$MEMORY/cloud-worker.env.local" ]]; then
    :
  else
    echo "# Добавьте carusel-memory/cloud-worker.env.local (WORKER_API_KEY, PROJECT_ID, CLOUD_RUN_API_KEY)"
  fi
} > "$ROOT/deploy/cloud-worker/.env.deploy.yaml"

# shell env для deploy.sh / setup-scheduler.sh
{
  echo "# generated by prepare_cloud_env.sh"
  [[ -f "$MEMORY/cloud-worker.env.local" ]] && grep -v '^#' "$MEMORY/cloud-worker.env.local" | grep '=' || true
} > "$ROOT/deploy/cloud-worker/.env.deploy"

echo "Wrote deploy/cloud-worker/.env.deploy.yaml"
echo "Wrote deploy/cloud-worker/.env.deploy"
echo "Проверьте WORKER_API_KEY, PROJECT_ID и CLOUD_RUN_API_KEY в cloud-worker.env.local"
